---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-ca-import-job

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-ca-import-job
rules:
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - "*"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-ca-import-job
roleRef:
  kind: Role
  name: vault-ca-import-job
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: vault-ca-import-job

---
apiVersion: batch/v1
kind: Job
metadata:
  name: import-ca
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      serviceAccountName: vault-ca-import-job
      containers:
      - name: import-ca
        image: bitnami/kubectl

        command: ["/bin/sh", "-c"]
        args:
          - cat /opt/tls/root-srv.pem /opt/tls/vault-root-ca.1.pem /opt/tls/vault-root-ca.2.pem > /tmp/ca.crt && kubectl create secret generic vault-ca --dry-run=client --save-config --from-file=ca.crt=/tmp/ca.crt --output yaml | kubectl apply -f -
        volumeMounts:
        - name: ca-crt
          mountPath: /opt/tls/ca.crt
            
      restartPolicy: Never
      volumes:
      - name: ca-crt
        hostPath:
          path: /etc/pki/tls/certs/
