# Define the files which contains the configs 
devices: generated/devices.yaml
groups: generated/groups.yaml

frontend:
  # Optional, default 8080
  port: 8080
  # Optional, default 0.0.0.0
  host: '0.0.0.0'
  # Optional, url on which the frontend can be reached, currently only used for the Home Assistant device configuration page
  url: 'https://zigbee2mqtt.dmann.xyz'

# Home Assistant integration (MQTT discovery)
homeassistant: true

# allow new devices to join
permit_join: false

# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL
  server: 'mqtts://mqtt.dmann.xyz:443'
  ca: /etc/ssl/certs/ca-certificates.crt
  # MQTT server authentication, uncomment if required:
  # user: my_user
  # password: my_password

# Serial settings
serial:
  adapter: deconz
  # Location of CC2531 USB sniffer
  port: "tcp://WLAN_raspberrypi.lan.house.dmann.xyz:20108"