apiVersion: v1
kind: Service
metadata:
  name: tautulli-ingress
  annotations:
    k8s.dmann.xyz/cloudflare-domain-dmann-xyz: tautulli
    k8s.dmann.xyz/cloudflare-zone-dmann-xyz: dmann.xyz
    k8s.dmann.xyz/cloudflare-domain-dmann-dev: tautulli
    k8s.dmann.xyz/cloudflare-zone-dmann-dev: dmann.dev
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: oauth2-https
  - name: http
    port: 80
    protocol: TCP
    targetPort: oauth2-http
  selector:
    app: tautulli
  sessionAffinity: None
  type: ClusterIP