apiVersion: v1
kind: Service
metadata:
  name: tautulli
spec:
  clusterIP: None
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv4
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: oauth2-proxy-https
  - name: http
    port: 80
    protocol: TCP
    targetPort: oauth2-proxy-http
  - name: tautulli
    port: 8181
    protocol: TCP
    targetPort: webui
  selector:
    app: tautulli