apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../common/components/ca-import

resources:
- ingress.yaml
helmCharts:
- name: traefik
  repo: https://helm.traefik.io/traefik
  version: v10.14.0
  releaseName: traefik
  namespace: traefik-system
  includeCRDs: true
  valuesInline:
    additionalArguments:
    - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
    - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
    - "--certificatesresolvers.homelab.acme.tlschallenge=true"

    - "--certificatesresolvers.homelab.acme.caserver=https://certificate-authority.internal.homelab.dmann.xyz/acme/acme/directory"
    - "--certificatesresolvers.homelab.acme.email=ninja@codingninja.com.au"
    - "--certificatesresolvers.homelab.acme.storage=/data/acme-homelab.json"
    - --providers.kubernetesIngress
    - --providers.kubernetesIngress.ingressEndpoint.publishedService=traefik-system/traefik
    dashboard:
      enable: false
    persistence:
      enabled: true
    ports:
      websecure:
        tls:
          enabled: true
          certResolver: "homelab"
        exposedPort: 2222
      gitlab:
        port: 2222
        exposedPort: 2222
        exposed: true
        protocol: TCP
    logs:
      general:
        level: info
      access:
        enabled: true
    env:
    - name: LEGO_CA_CERTIFICATES
      value: /certs/ca.crt
    - name: RFC2136_NAMESERVER
      value: homelab.ns.dmann.xyz
# Additional volumeMounts to add to the Traefik container
    volumes:
    - name: vault-ca
      type: secret
      mountPath: /certs