apiVersion: v1
kind: Service
metadata:
  name: prowlarr
spec:
  clusterIP: None
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv4
  selector:
    app: prowlarr
  ports:
  - port: 9696
    targetPort: webui