apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prowlarr
spec:
  serviceName: prowlarr
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-limits-cpu: 100m
        vault.hashicorp.com/agent-requests-cpu: 50m
        vault.hashicorp.com/agent-limits-mem: 128mi
        vault.hashicorp.com/agent-requests-mem: 64mi
        vault.hashicorp.com/role: prowlarr
        vault.hashicorp.com/agent-inject-secret-oidc: identity/oidc/client/prowlarr
        vault.hashicorp.com/agent-inject-template-oidc: |
          {{- with secret "identity/oidc/client/prowlarr" -}}
          export oidc_client_id="{{ .Data.client_id }}"
          export oidc_client_secret="{{ .Data.client_secret }}"
          {{- end }}
    spec:
      serviceAccount: prowlarr
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      volumes:
      - name: prowlarr-tls
        secret:
          secretName: prowlarr-tls
          defaultMode: 0777
      - name: media-nfs
        nfs:
          server: ceph.homelab.dmann.xyz
          path: /homelab/media
      - name: prowlarr-config-data
        persistentVolumeClaim:
          claimName: prowlarr-config-data
      containers:
      - name: oauth2-proxy
        command:
        - sh
        - -c
        args:
        - |
          source /vault/secrets/oidc;
          /bin/oauth2-proxy \
          --provider=oidc \
          --email-domain=* \
          --oidc-email-claim=sub \
          --upstream=http://127.0.0.1:9696 \
          --https-address=[::]:4180 \
          --tls-cert-file=/opt/prowlarr-tls/tls.crt \
          --tls-key-file=/opt/prowlarr-tls/tls.key \
          --provider-display-name="Vault" \
          --client-id="${oidc_client_id}" \
          --client-secret="${oidc_client_secret}" \
          --redirect-url="https://prowlarr.dmann.xyz" \
          --oidc-issuer-url="https://vault.homelab.dmann.xyz:8200/v1/identity/oidc/provider/default" \
          --cookie-secure=false \
          --cookie-secret=secret12secret12
        env: []
        image: harbor.dmann.dev/quay.io/oauth2-proxy/oauth2-proxy:latest
        ports:
        - containerPort: 4180
          protocol: TCP
          name: oauth2-proxy
        resources: 
        volumeMounts:
        - name: prowlarr-tls
          mountPath: /opt/prowlarr-tls
      - name: prowlarr
        image: lscr.io/linuxserver/prowlarr:develop
        volumeMounts:
        - name: media-nfs
          mountPath: /media
        - name: prowlarr-config-data
          mountPath: /config
        - name: prowlarr-tls
          mountPath: /opt/prowlarr-tls
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Australia/Sydney"

        ports:
        - name:  webui
          containerPort:  9696
          protocol: TCP
        resources:
        #   limits:
        #     memory: "4Gi"
        #     cpu: "4"