secrets: /vault/secrets/config
appdaemon:
  time_zone: CET
  latitude: 51.725
  longitude: 14.3434
  elevation: 0
  plugins:
    HASS:
      type: hass
      ha_url: https://home-assistant.dmann.xyz
      token: !secret home_assistant_token