apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-assistant-tls
spec:
  secretName: home-assistant-tls
  dnsNames:
    - home-assistant.dmann.xyz
    - home-assistant.dmann.dev
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer