apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: home-assistant
spec:
  serviceName: home-assistant-statufulset
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      hostNetwork: false
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      volumes:
      - name: home-assistant-tls
        secret:
          secretName: home-assistant-tls
          defaultMode: 0777
      - name: home-assistant-config
        configMap:
          name: home-assistant-config
      - name: nfs-volume
        nfs:
          server: ceph.homelab.dmann.xyz
          path: /homelab/media

      containers:
      - name: home-assistant
        image: ghcr.io/home-assistant/home-assistant:stable
        volumeMounts:
        - name: data
          mountPath: /config
        - name: nfs-volume
          mountPath: /media
        - name: home-assistant-config
          mountPath: /config/configuration.yaml
          subPath: configuration.yaml
          readOnly: true
        - name: home-assistant-tls
          mountPath: /opt/home-assistant-tls
        ports:
        - name:  webui
          containerPort:  8123
          protocol: TCP
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: ceph-retain
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
        #   limits:
        #     memory: "4Gi"
        #     cpu: "4"