apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: home-assistant
spec:
  serviceName: home-assistant-statufulset
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      hostNetwork: false
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      volumes:
      - name: home-assistant-tls
        secret:
          secretName: home-assistant-tls
          defaultMode: 0777
      - name: home-assistant-config
        configMap:
          name: home-assistant-config
      - name: home-assistant-packages
        configMap:
          name: home-assistant-packages
      - name: nfs-volume
        nfs:
          server: ceph.homelab.dmann.xyz
          path: /homelab/media
      - name: mdns-tunnel-config
        configMap:
          name: mdns-tunnel-config
      containers:
      - name: home-assistant
        image: ghcr.io/home-assistant/home-assistant:stable
        securityContext:
          capabilities:
            add:
            - CAP_NET_RAW
        volumeMounts:
        - name: data
          mountPath: /config
        - name: nfs-volume
          mountPath: /media
        - name: nfs-volume
          mountPath: /config/backups
          subPath: backups/home-assistant
        - name: nfs-volume
          mountPath: /config/custom_components
          subPath: home-assistant/custom_components
        - name: nfs-volume
          mountPath: /config/automations.yaml
          subPath: home-assistant/automations.yaml
        - name: home-assistant-packages
          mountPath: /config/packages
        - name: home-assistant-config
          mountPath: /config/configuration.yaml
          subPath: configuration.yaml
          readOnly: true
        - name: home-assistant-tls
          mountPath: /opt/home-assistant-tls
        ports:
        - name:  webui
          containerPort:  8123
          protocol: TCP
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
        readinessProbe:
          httpGet:
            path: /manifest.json
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /manifest.json
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
      - name: mdns-tunnel
        image: harbor.dmann.dev/docker.io/toxuin/mdns-tunneller
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: DEBUG
          value: '*' 
        ports:
        - name: tunnel
          containerPort: 42069
          protocol: TCP
        volumeMounts:
        - name: mdns-tunnel-config
          mountPath: /app/config
  volumeClaimTemplates:
  - apiVersion: v1		
    kind: PersistentVolumeClaim
    metadata:
      name: data
    spec:
      storageClassName: ceph-retain
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
        #   limits:
        #     memory: "4Gi"
        #     cpu: "4"