apiVersion: v1
kind: Service
metadata:
  name: home-assistant-statefulset
  namespace: home-assistant
spec:
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv4
  clusterIP: None
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: webui
  selector:
    app: home-assistant
  type: ClusterIP