apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: postgres-config
    literals:
      - POSTGRES_DB=postgresdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=psltest

  - name: home-assistant-config
    files:
      - configuration.yaml=config/configuration.yaml
  - name: mdns-tunnel-config
    files:
    - default.yaml=config/mdns-tunnel-default.yaml
resources:
- config/packages
- statefulset.yaml
- postgres-statefulset.yaml
- service.yaml
- postgres-service.yaml
- ingress.yaml
- certificate.yaml
