apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: home-assistant-config
    files:
      - configuration.yaml=config/configuration.yaml
  - name: mdns-tunnel-config
    files:
    - default.yaml=config/mdns-tunnel-default.yaml
resources:
- ../../../common/components/postgres
- config/packages
- statefulset.yaml
- service.yaml
- ingress.yaml
- certificate.yaml
