apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: home-assistant-config
    files:
      - configuration.yaml=config/configuration.yaml
resources:
- deployment.yaml
- service.yaml
- certificate.yaml
