apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - home-assistant
                topologyKey: "kubernetes.io/hostname"
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      containers:
      - name: postgres
        image: postgres:15.3 # Sets Image
        ports:
        - containerPort: 5432
          name: postgres
        envFrom:
        - configMapRef:
            name: postgres-config
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: data
  volumeClaimTemplates: 
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: data
    spec:
      storageClassName: ceph-retain
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
