apiVersion: v1
kind: Service
metadata:
  name: home-assistant-ingress
  namespace: home-assistant
  annotations:
    k8s.dmann.xyz/cloudflare-domain-dmann-xyz: home-assistant
    k8s.dmann.xyz/cloudflare-zone-dmann-xyz: dmann.xyz
    k8s.dmann.xyz/cloudflare-domain-dmann-dev: home-assistant
    k8s.dmann.xyz/cloudflare-zone-dmann-dev: dmann.dev
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: webui
  selector:
    app: home-assistant
  sessionAffinity: None
  type: ClusterIP