apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: tls-pkcs12-password
    options:
      disableNameSuffixHash: true
    literals:
      - password=password

resources:
- proxy
- deployment.yaml
- pvc.yaml
- service.yaml
- certificate.yaml
