apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex-server
  template:
    metadata:
      labels:
        app: plex-server
    spec:
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      volumes:
      - name: media-nfs
        nfs:
          server: ceph.homelab.dmann.xyz
          path: /homelab/media
          readOnly: true
      - name: plex-config-data
        persistentVolumeClaim:
          claimName: plex-config-data
      - name: transcode-storage # Idea being we would mount a dedicated ssd storage class pvc here
        emptyDir: {}
      containers:
      - name: plex-server
        image: plexinc/pms-docker
        volumeMounts:
        - name: media-nfs
          mountPath: /media
        - name: plex-config-data
          mountPath: /config
        - name: transcode-storage
          mountPath: /transcode
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: VERSION
          value: "docker"
        - name: ALLOWED_NETWORKS
          value: "10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,2403:5806:97ec::/48"

        ports:
        - name:  webui
          containerPort:  32400
          protocol: TCP
        - containerPort:  3005
          protocol: TCP
        - containerPort:  8324
          protocol: TCP
        - containerPort:  32469
          protocol: TCP
        
        - containerPort:  32410
          protocol: UDP
        - containerPort:  32412
          protocol: UDP
        - containerPort:  32413
          protocol: UDP
        - containerPort:  32414
          protocol: UDP
        resources:
        #   limits:
        #     memory: "4Gi"
        #     cpu: "4"