apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: workshop-tls
spec:
  secretName: workshop-tls
  dnsNames:
    - kubernetes.workshops.dmann.xyz
    - kubernetes.workshops.dmann.dev
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer