apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: caddyfile
    files:
    - "Caddyfile=./config/Caddyfile"
resources:
  - deployment.yaml
  - service.yaml
  - certificate.yaml

images:
  - name: k8-workshop
    newName: harbor.dmann.dev/library/k8-workshop
    newTag: v0.0.1-RC4