apiVersion: v1
kind: Service
metadata:
  name: workshop
  annotations:
    k8s.dmann.xyz/cloudflare-domain-dmann-xyz: kubernetes.workshops
    k8s.dmann.xyz/cloudflare-zone-dmann-xyz: dmann.xyz
    k8s.dmann.xyz/cloudflare-domain-dmann-dev: kubernetes.workshops
    k8s.dmann.xyz/cloudflare-zone-dmann-dev: dmann.dev
spec:
  selector:
    app: workshop
  ipFamilyPolicy: PreferDualStack
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
