apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: uptime-kuma-tls
spec:
  secretName: uptime-kuma-tls
  dnsNames:
    - status.dmann.xyz
    - status.dmann.dev
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer