apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
spec:
  ports:
  - name: http
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: uptime-kuma
    app.kubernetes.io/name: uptime-kuma
  type: ClusterIP