fridge_temp:
  sensor:
    - platform: derivative # will be positive for rising temperatures and negative for falling temperatures
      source: sensor.temperature
      unit_time: min
      # unique_id: fridge_temperature_derivative
      time_window: 00:05:00
  binary_sensor:
    - platform: threshold # will switch state not at 0째C/min but 0.1째C/min or -0.1째C/min depending on the current state of the sensor, respectively
      entity_id: sensor.fridge_temperature_derivative
      upper: 5
      hysteresis: 0.1 # sensor
      name: temperature rising

  # automation fridge_temp:
  # - alias: "Notify when the fridge temp rises above the threshold"
  #   id: fridge_above_threshold
  #   trigger:
  #   - platform: numeric_state
  #     entity_id:
  #       - sensor.0xa4c138e9aada1343_temperature
  #     above: input_number.fridge_warning_limit
  #     for:
  #       minutes: 2
  #   action:
  #     service: notify.notify
  #     data:
  #       title: Fridge warning
  #       message: "The fridge temperature is {{ states('sensor.0xa4c138e9aada1343_temperature') }}째C."