apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: home-assistant-packages
    files:
      - water_ph.yaml
      - homekit.yaml
      - washing_machine.yaml.yaml