apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: home-assistant-packages
  options:
    disableNameSuffixHash: true
  files:
  - fridge_temp.yaml
  - water_ph.yaml
  - homekit.yaml
  - prometheus.yaml
  - washing_machine.yaml