# This was written by ChatGPT...
water_ph:
  sensor:
  - platform: statistics
    unique_id: calibrated_ph_sensor_statistic
    name: "Calibrated PH value"
    entity_id: sensor.calibrated_ph
    state_characteristic: average_linear
    max_age:
      minutes: 30
    sampling_size: 50