# This was written by ChatGPT...
water_ph:
  input_number:
    min_calibrate_ph_value:
      name: Calibrated PH minimum
      initial: 4
      min: 0
      max: 7
    max_calibrate_ph_value:
      name: Calibrated PH maximum
      initial: 7
      min: 0
      max: 7
    ph_sensor_min_calibrate_value:
      name: Sensors minimum
      initial: 0
      min: 0
      max: 3
      step: 0.01
    ph_sensor_max_calibrate_value:
      name: Sensors maximum
      initial: 2
      min: 0
      max: 3
      step: 0.01

  template:
  - sensor:
    - name: "calibrated_ph_sensor"
      state: >
        {% set min_ph_value = states('input_number.min_calibrate_ph_value') | float %}
        {% set max_ph_value = states('input_number.max_calibrate_ph_value') | float %}
        {% set max_sensor_value = states('input_number.ph_sensor_max_calibrate_value') | float %}
        {% set min_sensor_value = states('input_number.ph_sensor_min_calibrate_value') | float %}
        {% set sensor_water_ph = states('sensor.water_ph') | float %}

        {{ (max_ph_value - min_ph_value) / (max_sensor_value - min_sensor_value) * (sensor_water_ph - min_sensor_value) + min_ph_value }}

  sensor:
  - platform: statistics
    unique_id: calibrated_ph_sensor_statistic
    name: "Calibrated PH value"
    entity_id: sensor.calibrated_ph_sensor
    state_characteristic: average_linear
    max_age:
      minutes: 30
    sampling_size: 50