apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflare-dns

resources:
- event-bus.yaml
- webhook-event-source.yaml
- resource-event-source.yaml
- service-event-sensor.yaml
- webhook-event-sensor.yaml
- workflow-template.yaml
- event-rbac.yaml
- wf-rbac.yaml
- vault-rbac.yaml
- oidc-secretclass.yaml