apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: cloudflare-dns-updater
spec:
  template:
    dnsConfig:
      options:
      - name: ndots
        value: "1"
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    # event-source can run multiple HTTP servers. Simply define a unique port to start a new HTTP server
    annotation-updated:
      # port to run HTTP server on
      port: "12000"
      # endpoint to listen to
      endpoint: /annotation-updated
      # HTTP request method to allow. In this case, only POST requests are accepted
      method: POST