apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudflaredns-workflow-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-executor
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflowtaskresults
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-executor
roleRef:
  kind: Role
  name: workflow-executor
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: cloudflaredns-workflow-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudflaredns-event-sources-workflow-discover
roleRef:
  kind: ClusterRole
  name: cloudflaredns-event-sources-discover
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: cloudflaredns-workflow-sa
  namespace: cloudflare-dns