apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: overseer
  template:
    metadata:
      labels:
        app: overseer
    spec:
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      volumes:
      - name: overseer-tls
        secret:
          secretName: overseer-tls
          defaultMode: 0777
      - name: caddyfile
        configMap:
            name: caddyfile
      - name: media-nfs
        nfs:
          server: ceph.homelab.dmann.xyz
          path: /homelab/media
      - name: overseer-config-data
        persistentVolumeClaim:
          claimName: overseer-config-data
      containers:
      - name: proxy
        image: docker.io/caddy:latest
        volumeMounts:
        - name: caddyfile
          mountPath: /opt/caddyfile
        - name: overseer-tls
          mountPath: /opt/overseer-tls
        readinessProbe:
          httpGet:
            path: /live
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /live
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        command:
        - caddy
        args:
        - run
        - --config
        - /opt/caddyfile/Caddyfile
        ports:
        - name:  http
          containerPort: 80
          protocol: TCP
        - name:  https
          containerPort: 443
          protocol: TCP
        resources:
      - name: overseer
        image: lscr.io/linuxserver/overseerr:latest@sha256:cd453f6c5de66719dc4cbb8e5dc22e4f12756f82e6afa2a98fd44e1720de76e4
        volumeMounts:
        - name: media-nfs
          mountPath: /media
        - name: overseer-config-data
          mountPath: /config
        - name: overseer-tls
          mountPath: /opt/overseer-tls
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Australia/Sydney"

        ports:
        - name:  webui
          containerPort:  5055
          protocol: TCP
        resources:
        #   limits:
        #     memory: "4Gi"
        #     cpu: "4"