apiVersion: v1
kind: Service
metadata:
  name: overseer-ingress
  annotations:
    k8s.dmann.xyz/cloudflare-domain-dmann-xyz: overseer
    k8s.dmann.xyz/cloudflare-zone-dmann-xyz: dmann.xyz
    k8s.dmann.xyz/cloudflare-domain-dmann-dev: overseer
    k8s.dmann.xyz/cloudflare-zone-dmann-dev: dmann.dev
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: overseer
  sessionAffinity: None
  type: ClusterIP