apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseer-config-data
spec:
  resources:
    requests:
      storage: 100G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-retain