apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:2.0.15-openssl
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: mqtt
          containerPort: 1883
          protocol: TCP
        - name: ws
          containerPort: 9001
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: mqtt
        readinessProbe:
          tcpSocket:
            port: mqtt
        volumeMounts:
        - name: mosquitto-config
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
        - name: mosquitto-tls
          mountPath: /opt/mosquitto-tls
      volumes:
      - name: mosquitto-config
        configMap:
          name: mosquitto-config
      - name: mosquitto-tls
        secret:
          secretName: mosquitto-tls