apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdaemon
spec:
  selector:
    matchLabels:
      app: appdaemon
  template:
    metadata:
      labels:
        app: appdaemon

      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-secret-config: secret/data/appdaemon/home-assistant-api
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/data/appdaemon/home-assistant-api" -}}
          home_assistant_token: "{{ .Data.data.token }}"
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-oidc: identity/oidc/client/appdaemon
        vault.hashicorp.com/agent-inject-template-oidc: |
          {{- with secret "identity/oidc/client/appdaemon" -}}
          export oidc_client_id="{{ .Data.data.client_id }}"
          export oidc_client_secret="{{ .Data.data.client_secret }}"
          {{- end }}
        vault.hashicorp.com/role: appdaemon
    spec:
      serviceAccount: appdaemon
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      volumes:
      - name: appdaemon-config
        configMap:
          name: appdaemon-config
      - name: appdaemon-data
        emptyDir: { } # todo make a PVC
      containers:
      - name: oauth2-proxy
        command:
        - sh
        - -c
        args:
        - |
          source /vault/secrets/oidc;
          /bin/oauth2-proxy \
          -provider oidc \
          -email-domain=codingninja.com.au \
          -upstream=tcp:///localhost:80 \
          -http-address=0.0.0.0:4180 \
          -provider-display-name "Vault" \
          -client-id ${oidc_client_id} \
          -client-secret ${oidc_client_secret} \
          -redirect-url https://appdaemon.dmann.xyz \
          -oidc-issuer-url https://vault.homelab.dmann.xyz:8200/v1/identity/oidc/provider/default \
          -cookie-secure=false \
          -cookie-secret=secret
        env: []
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        ports:
        - containerPort: 4180
          protocol: TCP
        resources: 
      - name: appdaemon
        image: harbor.dmann.dev/docker.io/acockburn/appdaemon:latest
        env:
        - name: DASH_URL
          value: https://appdaemon.dmann.xyz
        - name: HA_URL
          value: https://home-assistant.dmann.xyz
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - name: appdaemon-config
            mountPath: /conf/appdaemon.yaml 
            subPath: appdaemon.yaml
          - name: appdaemon-data
            mountPath: /opt/appdaemon-conf
        ports:
        - name: webui
          containerPort: 80
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: webui
        # readinessProbe:
        #   tcpSocket:
        #     port: webui