apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdaemon
spec:
  selector:
    matchLabels:
      app: appdaemon
  template:
    metadata:
      labels:
        app: appdaemon
    spec:
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      containers:
      - name: appdaemon
        image: harbor.dmann.dev/docker.io/acockburn/appdaemon:latest
        env:
        - name: DASH_URL
          value: https://appdaemon.dmann.xyz
        - name: HA_URL
          value: https://home-assistant.dmann.xyz
        - name: TOKEN
          value: https://appdaemon.dmann.xyz
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: webui
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: webui
        readinessProbe:
          tcpSocket:
            port: webui