apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdaemon
spec:
  selector:
    matchLabels:
      app: appdaemon
  template:
    metadata:
      labels:
        app: appdaemon

      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-secret-config: secret/data/appdaemon/home-assistant-api
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/data/appdaemon/home-assistant-api" -}}
          home_assistant_token: {{ .Data.data.token }}
          {{- end }}
        vault.hashicorp.com/role: appdaemon
    spec:
      serviceAccount: appdaemon
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      containers:
      - name: appdaemon
        image: harbor.dmann.dev/docker.io/acockburn/appdaemon:latest
        env:
        - name: DASH_URL
          value: https://appdaemon.dmann.xyz
        - name: HA_URL
          value: https://home-assistant.dmann.xyz
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: webui
          containerPort: 80
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: webui
        readinessProbe:
          tcpSocket:
            port: webui