apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdaemon
spec:
  selector:
    matchLabels:
      app: appdaemon
  template:
    metadata:
      labels:
        app: appdaemon
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-limits-cpu: 100m
        vault.hashicorp.com/agent-requests-cpu: 50m
        vault.hashicorp.com/agent-limits-mem: 128Mi
        vault.hashicorp.com/agent-requests-mem: 64Mi
        vault.hashicorp.com/agent-inject-secret-config: secret/data/appdaemon/home-assistant-api
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/data/appdaemon/home-assistant-api" -}}
          home_assistant_token: "{{ .Data.data.token }}"
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-oidc: identity/oidc/client/appdaemon
        vault.hashicorp.com/agent-inject-template-oidc: |
          {{- with secret "identity/oidc/client/appdaemon" -}}
          export oidc_client_id="{{ .Data.client_id }}"
          export oidc_client_secret="{{ .Data.client_secret }}"
          {{- end }}
        vault.hashicorp.com/role: appdaemon
    spec:
      serviceAccount: appdaemon
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      volumes:
      - name: appdaemon-config
        configMap:
          name: appdaemon-config
      - name: appdaemon-apps
        configMap:
          name: appdaemon-apps
      - name: appdaemon-tls
        secret:
          secretName: appdaemon-tls
      containers:
      - name: oauth2-proxy
        command:
        - sh
        - -c
        args:
        - |
          source /vault/secrets/oidc;
          /bin/oauth2-proxy \
          --provider=oidc \
          --email-domain=* \
          --oidc-email-claim=sub \
          --upstream=http://127.0.0.1:80 \
          --https-address=[::]:4180 \
          --tls-cert-file=/opt/appdaemon-tls/tls.crt \
          --tls-key-file=/opt/appdaemon-tls/tls.key \
          --provider-display-name="Vault" \
          --client-id="${oidc_client_id}" \
          --client-secret="${oidc_client_secret}" \
          --redirect-url="https://appdaemon.dmann.xyz" \
          --oidc-issuer-url="https://vault.homelab.dmann.xyz:8200/v1/identity/oidc/provider/default" \
          --cookie-secure=false \
          --cookie-secret=secret12secret12
        env: []
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        ports:
        - containerPort: 4180
          protocol: TCP
          name: oauth2-proxy
        resources: 
        volumeMounts:
        - name: appdaemon-tls
          mountPath: /opt/appdaemon-tls
      - name: appdaemon
        image: docker.io/acockburn/appdaemon:latest
        env:
        - name: DASH_URL
          value: https://appdaemon.dmann.xyz
        - name: HA_URL
          value: https://home-assistant.dmann.xyz
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: appdaemon-config
          mountPath: /conf/appdaemon.yaml 
          subPath: appdaemon.yaml
        - name: appdaemon-apps
          mountPath: /opt/appdaemon-apps
        ports:
        - name: webui
          containerPort: 80
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: webui