apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdaemon
spec:
  selector:
    matchLabels:
      app: appdaemon
  template:
    metadata:
      labels:
        app: appdaemon
    spec:
      serviceAccount: appdaemon
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      containers:
      - name: appdaemon
        image: harbor.dmann.dev/docker.io/acockburn/appdaemon:latest
        env:
        - name: DASH_URL
          value: https://appdaemon.dmann.xyz
        - name: HA_URL
          value: https://home-assistant.dmann.xyz
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-hass-api-secret
              key: token
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: webui
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: webui
        readinessProbe:
          tcpSocket:
            port: webui
      volumeMounts:
      - mountPath: /run/secrets/hass-api
        name: hass-api-token
    volumes:
    - csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: vault-hass-api
      name: hass-api-token