apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator: 
  - name: appdaemon-config
    options:
      disableNameSuffixHash: true
    files:
    - env.py=apps/env.py
    - apps.yaml=config/apps.yaml
  - name: appdaemon-config
    files:
    - appdaemon.yaml=config/appdaemon.yaml
resources:
- deployment.yaml
- service.yaml
- certificate.yaml
- sa.yaml
- vault-rbac.yaml