apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator: 
  - name: appdaemon-config
    files:
    - appdaemon.yaml=config/appdaemon.yaml
resources:
- proxy
- deployment.yaml
- service.yaml
- certificate.yaml
- sa.yaml
- vault-rbac.yaml