apiVersion: v1
kind: Service
metadata:
  name: appdaemon
spec:
  clusterIP: None
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv4
  selector:
    app: appdaemon
  ports:
  - port: 80
    targetPort: webui