apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitea-event-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitea-event-sources-workflow
rules:
- apiGroups:
    - "argoproj.io"
  resources:
    - "workflows"
  verbs:
    - create
    - list
    - get
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitea-event-sources-workflow
roleRef:
  kind: Role
  name: gitea-event-sources-workflow
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: gitea-event-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitea-event-sources-discover
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitea-event-sources
roleRef:
  kind: ClusterRole
  name: gitea-event-sources-discover
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: gitea-event-sa
  namespace: default
