apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- oidc-secretclass.yaml
- vault-rbac.yaml
- wf-rbac.yaml
- workflow-event-binding.yaml
- workflow-template.yaml
- event-bus.yaml
- webhook-event-sensor.yaml
- webhook-event-source.yaml