apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitea-webhook-sa
---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-webhook-sa.service-account-token
  annotations:
    kubernetes.io/service-account.name: gitea-webhook-sa
type: kubernetes.io/service-account-token
---
# Just enough permissions to submit a workflow template.
# You could tighten this further (but perhaps impractically) by using `resourceNames`
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitea-webhook-executor
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workfloweventbindings
  verbs:
  - list
- apiGroups:
  - argoproj.io
  resources:
  - workflowtemplates
  verbs:
  - get
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitea-webhook-sa-gitea-webhook-executor
roleRef:
  kind: Role
  name: gitea-webhook-executor
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: gitea-webhook-sa