apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: gitea-event
spec:
  template:
    serviceAccountName: gitea-event-sa
    dnsConfig:
      options:
      - name: ndots
        value: "1"
    container:
      env:
      - name: DEBUG_LOG
        value: "true"
  dependencies:
  - name: gitea-event-dep
    eventSourceName: gitea-webhook-event
    eventName: gitea-event
  triggers:
  - template:
      name: log-trigger2
      log:
        intervalSeconds: 4
  - template:
      name: argo-workflow-trigger
      argoWorkflow:
        operation: submit
        parameters:
        - src:
            dependencyName: gitea-event-dep
            dataKey: body.repository.clone_url
          dest: spec.arguments.parameters.0.value
        - src:
            dependencyName: gitea-event-dep
            dataKey: body.after
          dest: spec.arguments.parameters.1.value
        - src:
            dependencyName: gitea-event-dep
            dataTemplate: harbor.dmann.dev/default/{{ .Input.body.repository.full_name }}:{{ .Input.body.after }}
          dest: spec.arguments.parameters.2.value
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: image-pipeline-
            spec:
              serviceAccountName: image-pipeline-wf-sa
              entrypoint: main
              arguments:
                parameters:
                - name: repo
                  value: pending
                - name: revision
                  value: pending
                - name: destination
                  value: pending
              workflowTemplateRef:
                name: image-pipeline