apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-pipeline-wf-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-executor
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflowtaskresults
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-executor
roleRef:
  kind: Role
  name: workflow-executor
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: image-pipeline-wf-sa
