apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: image-pipeline
spec:
  entrypoint: main
  serviceAccountName: image-pipeline-wf-sa
  arguments:
    parameters:
    - name: raw
      value: "hello"
  templates:
  - name: main
    steps:
    - - name: default
        template: argosay
        arguments:
          parameters:
          - name: raw
            value: "{{workflow.parameters.raw}}"

  - name: argosay
    inputs:
      parameters:
      - name: raw
    container:
      image: argoproj/argosay:v2
      args: [ echo, "{{workflow.parameters}} {{inputs.parameters}}" ]