apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: image-pipeline
spec:
  entrypoint: main
  serviceAccountName: image-pipeline-wf-sa
  arguments:
    parameters:
    - name: salutation
      value: "hello"
    - name: appellation
      value: "sir"
  templates:
  - name: main
    steps:
    - - name: a
        template: argosay
        arguments:
          parameters:
          - name: salutation
            value: "{{workflow.parameters.salutation}}"
          - name: appellation
            value: "{{workflow.parameters.appellation}}"

  - name: argosay
    inputs:
      parameters:
      - name: salutation
      - name: appellation
    container:
      image: argoproj/argosay:v2
      args: [ echo, "{{workflow.parameters}} {{inputs.parameters}}" ]