apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: image-pipeline
spec:
  entrypoint: main
  serviceAccountName: image-pipeline-wf-sa
  arguments:
    parameters:
    - name: repository
    - name: revision
    - name: destination
  templates:
  - name: main
    inputs:
      artifacts:
      - name: source
        path: /src
        git:
          repo: "{{inputs.parameters.repository}}"
          revision: "{{inputs.parameters.revision}}"
    container:
      image: gcr.io/kaniko-project/executor
      args:
        - --context=/src
        - --destination={{inputs.parameters.destination}}
      volumeMounts:
      - name: docker-config
        mountPath: /kaniko/.docker/