apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: esphome-tls
spec:
  secretName: esphome-tls
  dnsNames:
    - esphome.dmann.xyz
    - esphome.dmann.dev
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer