apiVersion: apps/v1
kind: Deployment
metadata:
  name: esphome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esphome
  template:
    metadata:
      labels:
        app: esphome
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-limits-cpu: 100m
        vault.hashicorp.com/agent-requests-cpu: 50m
        vault.hashicorp.com/agent-limits-mem: 128Mi
        vault.hashicorp.com/agent-requests-mem: 64Mi
        vault.hashicorp.com/role: esphome
        vault.hashicorp.com/agent-inject-secret-oidc: identity/oidc/client/esphome
        vault.hashicorp.com/agent-inject-template-oidc: |
          {{- with secret "identity/oidc/client/esphome" -}}
          export oidc_client_id="{{ .Data.client_id }}"
          export oidc_client_secret="{{ .Data.client_secret }}"
          {{- end }}
    spec:
      serviceAccount: esphome
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      volumes:
      - name: esphome-tls
        secret:
          secretName: esphome-tls
          defaultMode: 0777
      - name: esphome-config
        configMap:
          name: esphome-config
      - name: nfs-volume
        nfs:
          server: ceph.homelab.dmann.xyz
          path: /homelab/media
      - name: esphome-cache
        persistentVolumeClaim:
          claimName: esphome-cache

      containers:
      - name: oauth2-proxy
        command:
        - sh
        - -c
        args:
        - |
          source /vault/secrets/oidc;
          /bin/oauth2-proxy \
          --provider=oidc \
          --email-domain=* \
          --oidc-email-claim=sub \
          --upstream=http://127.0.0.1:6052 \
          --https-address=[::]:4180 \
          --tls-cert-file=/opt/esphome-tls/tls.crt \
          --tls-key-file=/opt/esphome-tls/tls.key \
          --provider-display-name="Vault" \
          --client-id="${oidc_client_id}" \
          --client-secret="${oidc_client_secret}" \
          --redirect-url="https://esphome.dmann.xyz" \
          --oidc-issuer-url="https://vault.homelab.dmann.xyz:8200/v1/identity/oidc/provider/default" \
          --cookie-secure=false \
          --cookie-secret=secret12secret12
        env: []
        image: harbor.dmann.dev/quay.io/oauth2-proxy/oauth2-proxy:latest
        ports:
        - containerPort: 4180
          protocol: TCP
          name: oauth2-proxy
        resources: 
        volumeMounts:
        - name: esphome-tls
          mountPath: /opt/esphome-tls
      - name: esphome
        image: harbor.dmann.dev/docker.io/esphome/esphome:2023.1.0-dev20221216
        volumeMounts:
        - name: nfs-volume
          mountPath: /config
          subPath: esphome
        - name: esphome-cache
          mountPath: /config/.esphome
        ports:
        - name:  esphome
          containerPort:  6052
          protocol: TCP
        resources:
        #   limits:
        #     memory: "4Gi"
        #     cpu: "4"