apiVersion: v1
kind: Service
metadata:
  name: esphome
spec:
  clusterIP: None
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv4
  selector:
    app: esphome
  ports:
  - port: 6052
    targetPort: webui