apiVersion: v1
kind: Service
metadata:
  name: esphome-ingress
  annotations:
    k8s.dmann.xyz/cloudflare-domain-dmann-xyz: esphome
    k8s.dmann.xyz/cloudflare-zone-dmann-xyz: dmann.xyz
    k8s.dmann.xyz/cloudflare-domain-dmann-dev: esphome
    k8s.dmann.xyz/cloudflare-zone-dmann-dev: dmann.dev
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: oauth2-proxy
  selector:
    app: esphome
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: esphome
spec:
  clusterIP: None
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv4
  selector:
    app: esphome
  ports:
  - port: 6052
    targetPort: esphome