apiVersion: compute.ordiri.com/v1alpha1
kind: VirtualMachineDeployment
metadata:
  name: bastion
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
    spec:
      bootDevices:
      - hd
      - network
      networkInterfaces:
      - mac: ""
        network: kubevms
        subnet: kubevms-bastion
      node: ""
      role: default
      state: Running
      volumes:
      - device: vda
        hostLocal:
          poolName: bastion
          size: 5gi
          volName: root
        name: root