apiVersion: compute.ordiri.com/v1alpha1
kind: VirtualMachineDeployment
metadata:
  name: etcd
spec:
  replicas: 3
  template:
    metadata:
      creationTimestamp: null
    spec:
      resources:
        cpu: 2
        memory: 2Gi
      userData: !include etcd/preseed.sh
      bootDevices:
      - hd
      - network
      networkInterfaces:
      - mac: ""
        network: kubevms
        subnet: kubevms-etcd
      role: default
      state: Running
      volumes:
      - device: vda
        hostLocal:
          poolName: etcd
          size: 30Gi
          volName: root
        name: root