apiVersion: compute.ordiri.com/v1alpha1
kind: VirtualMachineDeployment
metadata:
  name: kube-workers
spec:
  replicas: 5
  template:
    metadata:
      creationTimestamp: null
    spec:
      userData: !include kube-workers/preseed.sh
      devices: # Passthrough a GPU device if there is one in the pool available
      - deviceClassName: DisplayVGA
        name: GPU
        optional: true
      bootDevices:
      - hd
      - network
      resources:
        cpu: 6
        memory: 16Gi
      networkInterfaces:
      - mac: ""
        network: kubevms
        subnet: kubevms-workers
      role: default
      state: Running
      volumes:
      - device: vda
        hostLocal:
          poolName: kube-workers
          size: 100Gi
          volName: root
        name: root