apiVersion: compute.ordiri.com/v1alpha1
kind: VirtualMachineDeployment
metadata:
  name: kube-master
spec:
  replicas: 3
  template:
    metadata:
      creationTimestamp: null
    spec:
      resources:
        cpu: 3
        memory: 4Gi
      userData: !include kube-masters/preseed.sh
      bootDevices:
      - hd
      - network
      networkInterfaces:
      - mac: ""
        network: kubevms
        public: true
        subnet: kubevms-masters
        dnsNames:
        - cluster.homelab.dmann.xyz
      role: default
      state: Running
      volumes:
      - device: vda
        hostLocal:
          poolName: kube-masters
          size: 30Gi
          volName: root
        name: root