apiVersion: compute.ordiri.com/v1alpha1
kind: VirtualMachineDeployment
metadata:
  name: kube-workers
spec:
  replicas: 3
  template:
    metadata:
      creationTimestamp: null
    spec:
      userData: !include kube-workers/preseed.sh
      bootDevices:
      - hd
      - network
      resources:
        cpu: 2
        memory: 4Gi
      networkInterfaces:
      - mac: ""
        network: kubevms
        subnet: kubevms-workers
      role: default
      state: Running
      volumes:
      - device: vda
        hostLocal:
          poolName: kube-workers
          size: 30Gi
          volName: root
        name: root