apiVersion: core.ordiri.com/v1alpha1
kind: MachineProfile
metadata:
  name: default
spec:
  files:
    preseed.cfg: !include machine-profile/preseed.cfg
  ipxeConfiguration:
    args:
      - initrd=initrd.gz
      - install
      - 'preseed/url=http://10.0.1.196:8090/fetch?&uuid=${uuid}&file=preseed.cfg'
      - debian-installer=en_US.UTF-8
      - auto
      - priority=critical
      - locale=en_US.UTF-8
      - kbd-chooser/method=us
      - keyboard-configuration/xkb-keymap=us
      - fb=false
      - debconf/frontend=noninteractive
      - netcfg/choose_interface=auto
      - console-setup/ask_detect=false
      - console-keymaps-at/keymap=us
    initrd:
      - >-
        http://deb.debian.org/debian/dists/bullseye/main/installer-amd64/current/images/netboot/debian-installer/amd64/initrd.gz
    kernel: >-
      http://deb.debian.org/debian/dists/bullseye/main/installer-amd64/current/images/netboot/debian-installer/amd64/linux
