apiVersion: core.ordiri.com/v1alpha1
kind: MachineProfile
metadata:
  name: default
spec:
  files:
    preseed.cfg: |
      # Preseeding only locale sets language, country and locale.
      d-i debian-installer/locale string en_US
      
      # Keyboard selection.
      d-i console-setup/ask_detect boolean false
      d-i keyboard-configuration/xkb-keymap select us
      
      choose-mirror-bin mirror/http/proxy string
      
      ### Clock and time zone setup
      d-i clock-setup/utc boolean true
      d-i time/zone string UTC
      
      # Avoid that last message about the install being complete.
      d-i finish-install/reboot_in_progress note
      
      # Ensure GRUB is setup on MBR
      d-i grub-installer/skip boolean false
      
      # Select the first disk in the list
      d-i grub-installer/bootdev  string default
      
      # This is fairly safe to set, it makes grub install automatically to the MBR
      # if no other operating system is detected on the machine.
      d-i grub-installer/only_debian boolean true
      
      # This one makes grub-installer install to the MBR if it also finds some other
      # OS, which is less safe as it might not be able to boot that other OS.
      d-i grub-installer/with_other_os boolean true
      
      ### Mirror settings
      # If you select ftp, the mirror/country string does not need to be set.
      # d-i mirror/country string manual
      # d-i mirror/http/directory string /ubuntu/
      # d-i mirror/http/hostname string archive.ubuntu.com
      # d-i mirror/http/proxy string
      
      ### Partitioning
      d-i partman-auto/method string lvm
      d-i partman-auto-lvm/guided_size string max
      d-i partman-auto/choose_recipe select atomic
      d-i partman-lvm/confirm boolean true
      d-i partman-lvm/confirm_nooverwrite boolean true
      
      # This makes partman automatically partition without confirmation.
      d-i partman-md/confirm boolean true
      d-i partman-partitioning/confirm_write_new_label boolean true
      d-i partman/choose_partition select finish
      d-i partman/confirm boolean true
      d-i partman/confirm_nooverwrite boolean true
      
      ### Account setup
      d-i passwd/root-login boolean false
      d-i passwd/root-password-again password password
      d-i passwd/root-password password password
      
      d-i passwd/user-fullname string ordiri
      d-i passwd/user-uid string 1000
      d-i passwd/user-password password password
      d-i passwd/user-password-again password password
      d-i passwd/username string ordiri
      
      d-i user-setup/allow-password-weak boolean true
      d-i user-setup/encrypt-home boolean false
      
      ### Package selection
      tasksel tasksel/first multiselect 
      d-i pkgsel/include string openssh-server build-essential
      d-i pkgsel/install-language-support boolean false
      
      # disable automatic package updates
      d-i pkgsel/update-policy select none
      d-i pkgsel/upgrade select safe-upgrade

      d-i preseed/late_command string in-target apt-get update ; \
          in-target apt-get -y dist-upgrade ; \
          in-target apt-get -y autoremove ; \
          in-target apt-get autoclean ; \
          in-target apt-get clean ; \
          in-target apt-get install curl ; \
          in-target curl -XGET http://169.254.169.254/latest/user-data -o /sbin/boot-server.sh ; \
          in-target chmod +x /sbin/boot-server.sh ; \
          in-target /sbin/boot-server.sh ;
  ipxeConfiguration:
    args:
      - initrd=initrd.gz
      - install
      - 'preseed/url=http://10.0.2.102:8090/fetch?&uuid=${uuid}&file=preseed.cfg'
      - debian-installer=en_US.UTF-8
      - auto
      - priority=critical
      - locale=en_US.UTF-8
      - kbd-chooser/method=us
      - keyboard-configuration/xkb-keymap=us
      - fb=false
      - debconf/frontend=noninteractive
      - netcfg/choose_interface=auto
      - console-setup/ask_detect=false
      - console-keymaps-at/keymap=us
    initrd:
      - >-
        http://deb.debian.org/debian/dists/bullseye/main/installer-amd64/current/images/netboot/debian-installer/amd64/initrd.gz
    kernel: >-
      http://deb.debian.org/debian/dists/bullseye/main/installer-amd64/current/images/netboot/debian-installer/amd64/linux
