apiVersion: network.ordiri.com/v1alpha1
kind: Subnet
metadata:
  name: kubevms-etcd
spec:
  cidr: 10.200.0.0/24
  cidr6: 2403:5807:c863:0200::/64
  dhcp:
    enabled: true
  network:
    name: kubevms
---
apiVersion: network.ordiri.com/v1alpha1
kind: Subnet
metadata:
  name: kubevms-masters
spec:
  cidr: 10.200.1.0/24
  cidr6: 2403:5807:c863:0201::/64
  dhcp:
    enabled: true
  network:
    name: kubevms
---
apiVersion: network.ordiri.com/v1alpha1
kind: Subnet
metadata:
  name: kubevms-workers
spec:
  cidr: 10.200.2.0/24
  cidr6: 2403:5807:c863:0202::/64
  dhcp:
    enabled: true
  network:
    name: kubevms

---
apiVersion: network.ordiri.com/v1alpha1
kind: Subnet
metadata:
  name: kubevms-vault
spec:
  cidr: 10.200.3.0/24
  cidr6: 2403:5807:c863:0203::/64
  dhcp:
    enabled: true
  network:
    name: kubevms