# Uses the root vault to unseal by
# logging in via a CIDR bound app role
# which should be converted to use 
# some oidc provider setup where ordiri 
# provides an identity to a vm and the vm
# logs into the root vault with that identity
# which root vault validates against the
# ordiri public api
apiVersion: compute.ordiri.com/v1alpha1
kind: VirtualMachineDeployment
metadata:
  name: vault
spec:
  replicas: 2
  template:
    metadata:
      creationTimestamp: null
    spec:
      resources:
        cpu: 1
        memory: 1Gi
      userData: !include vault/preseed.sh
      bootDevices:
      - hd
      - network
      networkInterfaces:
      - network: kubevms
        subnet: kubevms-vault
      role: default
      state: Running
      volumes:
      - device: vda
        hostLocal:
          poolName: vault
          size: 30Gi
          volName: root
        name: root