apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../common/components/ca-import
  
resources:
- upstream
- application-set.yaml
- ingress.yaml
- calico-app.yaml

images:
  - name: quay.io/argoproj/argocd
    newTag: 2.3.0-rc1

configMapGenerator:
- name: argocd-rbac-cm
  behavior: merge
  literals:
    - policy.default=role:admin

- name: argocd-cm
  behavior: merge
  files:
    - dex.config=dex.yaml
  literals:
    - url=https://argocd.homelab.dmann.xyz
    - users.anonymous.enabled=true
    - kustomize.buildOptions=--enable-helm

patchesStrategicMerge:
  - argocd-server-certificate-patch.yaml
  - dex-certificate-patch.yaml