roles:
  physical2: ~
  physical:
    ipxe:
      kernel: "http://deb.debian.org/debian/dists/bullseye/main/installer-amd64/current/images/netboot/debian-installer/amd64/linux"
      initrd:
      - "http://deb.debian.org/debian/dists/bullseye/main/installer-amd64/current/images/netboot/debian-installer/amd64/initrd.gz"
      args:
      - "initrd=initrd.gz"
      - "install"
      - "preseed/url=http://10.0.2.102:8090/fetch?&uuid=${uuid}&file=preseed.cfg"
      - "debian-installer=en_US.UTF-8"
      - "auto"
      - "priority=critical"
      - "locale=en_US.UTF-8"
      - "kbd-chooser/method=us"
      - "keyboard-configuration/xkb-keymap=us"
      - "fb=false"
      - "debconf/frontend=noninteractive"
      - "netcfg/choose_interface=auto"
      - "console-setup/ask_detect=false"
      - "console-keymaps-at/keymap=us"
      - "console=ttyS0,115200"
      - "serial"
    files:
      preseed.cfg: |
          choose-mirror-bin mirror/http/proxy string
          d-i apt-setup/use_mirror boolean true
          d-i base-installer/kernel/override-image string linux-server
          d-i clock-setup/utc boolean true
          d-i clock-setup/utc-auto boolean true
          d-i finish-install/reboot_in_progress note
          d-i grub-installer/skip boolean false
          d-i grub-installer/only_debian boolean true
          d-i grub-installer/with_other_os boolean true
          d-i keymap select us
          d-i mirror/country string manual
          d-i mirror/http/directory string /debian
          d-i mirror/http/hostname string httpredir.debian.org
          d-i mirror/http/proxy string

          d-i netcfg/choose_interface select auto

          d-i partman-auto-lvm/guided_size string max
          d-i partman-auto/choose_recipe select atomic
          d-i partman-auto/method string lvm
          d-i partman-lvm/confirm boolean true
          d-i partman-lvm/confirm_nooverwrite boolean true
          d-i partman/confirm_nooverwrite boolean true
          d-i partman-md/confirm_nooverwrite boolean true
          d-i partman-lvm/device_remove_lvm boolean true
          d-i partman/choose_partition select finish
          d-i partman/confirm boolean true
          d-i partman/confirm_nooverwrite boolean true
          d-i partman/confirm_write_new_label boolean true
          d-i passwd/root-login boolean false
          d-i passwd/root-password-again password password
          d-i passwd/root-password password password
          d-i passwd/user-fullname string david mann
          d-i passwd/user-uid string 999
          d-i passwd/user-password password password
          d-i passwd/user-password-again password password
          d-i passwd/username string user
          d-i pkgsel/include string  curl wget
          d-i pkgsel/install-language-support boolean false
          d-i pkgsel/update-policy select none
          d-i pkgsel/upgrade select full-upgrade
          # Prevent packaged version of VirtualBox Guest Additions being installed:
          d-i preseed/early_command string sed -i \
            '/in-target/idiscover(){/sbin/discover|grep -v VirtualBox;}' \
            /usr/lib/pre-pkgsel.d/20install-hwpackages
          d-i time/zone string UTC
          d-i user-setup/allow-password-weak boolean true
          d-i user-setup/encrypt-home boolean false
          d-i preseed/late_command string sed -i '/^deb cdrom:/s/^/#/' /target/etc/apt/sources.list
          apt-cdrom-setup apt-setup/cdrom/set-first boolean false
          apt-mirror-setup apt-setup/use_mirror boolean true
          popularity-contest popularity-contest/participate boolean false