apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../common/components/ca-import

# resources:
  # - ingress.yaml

helmCharts:
- name: harbor
  repo: https://helm.goharbor.io
  version: v1.8.1
  releaseName: harbor
  namespace: harbor
  includeCRDs: true
  valuesFile: values.yaml

patchesStrategicMerge:
  - |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: harbor-core
    spec:
      template:
        spec:
          containers:
          - name: core
            volumeMounts:
              - name: ca-certs
                mountPath: /etc/ssl/certs
          volumes:
            - name: ca-certs
              secret:
                secretName: vault-ca