apiVersion: apps/v1
kind: Deployment
metadata:
  name:  gitlab-webservice-default
  namespace: gitlab
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-init-first: "true" # We need this because we hack the cfgmap script to merge in our provider with vault details
        vault.hashicorp.com/role: gitlab-oidc
        vault.hashicorp.com/tls-secret: vault-ca
        vault.hashicorp.com/ca-cert: /vault/tls/ca.crt
        vault.hashicorp.com/agent-service-account-token-volume-name: api-access
        vault.hashicorp.com/agent-inject-secret-vault-oidc: identity/oidc/client/gitlab
        vault.hashicorp.com/agent-inject-template-vault-oidc: |
          {{- with secret "identity/oidc/client/gitlab" -}}
          name: openid_connect
          label: Vault # optional label for login button, defaults to "Openid Connect"
          # icon: <custom_provider_icon>
          args: 
            name: openid_connect
            scope: [ openid, groups, user ]
            response_type: code
            issuer: https://vault.homelab.dmann.xyz:8200/v1/identity/oidc/provider/homelab
            discovery: true
            uid_field: username
            client_options: 
              # TODO: Inject these somehow
              identifier: {{ .Data.client_id }}
              secret: {{ .Data.client_secret }}
              redirect_uri: https://gitlab.homelab.dmann.xyz/users/auth/openid_connect/callback
          {{- end -}}
    spec:
      # initContainers:
      # - name: dependencies
      #   volumeMounts:
      #   - name: vault-secrets
      #     mountPath: /vault/secrets
      #     readOnly: true
      volumes:
      # - name: vault-secrets
      #   emptyDir:
      #     medium: Memory
      - name: api-access
        projected:
          defaultMode: 420
          sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
              - key: ca.crt
                path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
              - fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
                path: namespace