apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-webservice-default
  namespace: gitlab
spec:
  template:
    spec:
      volumes:
      - name: puma-config
        configMap:
          name: puma-configuration
      containers:
        - name: webservice
          volumeMounts:
          - name: puma-config
            mountPath: /srv/gitlab/config/puma.rb
            subPath: puma.rb