apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bazarr-tls
spec:
  secretName: bazarr-tls
  dnsNames:
    - bazarr.dmann.xyz
    - bazarr.dmann.dev
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  keystores:
    pkcs12:
      create: true
      passwordSecretRef: 
        key: password
        name: tls-pkcs12-password