apiVersion: v1
kind: Service
metadata:
  name: bazarr-ingress
  annotations:
    k8s.dmann.xyz/cloudflare-domain-dmann-xyz: bazarr
    k8s.dmann.xyz/cloudflare-zone-dmann-xyz: dmann.xyz
    k8s.dmann.xyz/cloudflare-domain-dmann-dev: bazarr
    k8s.dmann.xyz/cloudflare-zone-dmann-dev: dmann.dev
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: oauth2-proxy
  selector:
    app: bazarr
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: bazarr
spec:
  clusterIP: None
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv4
  selector:
    app: bazarr
  ports:
  - port: 6767
    targetPort: webui