apiVersion: v1
kind: Service
metadata:
  name: bazarr
spec:
  clusterIP: None
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv4
  selector:
    app: bazarr
  ports:
  - port: 6767
    targetPort: webui