apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- external.yaml
- storage-class.yaml
# - nfs-rbac.yaml
# - ingress.yaml
helmCharts:
- name: rook-ceph
  repo: https://charts.rook.io/release
  version: v1.10.4
  releaseName: rook-ceph
  namespace: rook-ceph
  includeCRDs: true
  valuesInline:
    csi:
      enableCephfsDriver: false
      enableGrpcMetrics: false
      # Set to true to enable host networking for CSI CephFS and RBD nodeplugins. This may be necessary
      # in some network configurations where the SDN does not provide access to an external cluster or
      # there is significant drop in read/write performance.
      enableCSIHostNetwork: false
      # set to false to disable deployment of snapshotter container in CephFS provisioner pod.
      enableCephfsSnapshotter: false
      # set to false to disable deployment of snapshotter container in NFS provisioner pod.
      enableNFSSnapshotter: false
      # set to false to disable deployment of snapshotter container in RBD provisioner pod.
      enableRBDSnapshotter: true
      # set to false if the selinux is not enabled or unavailable in cluster nodes.
      enablePluginSelinuxHostMount: false
      # set to true to enable Ceph CSI pvc encryption support.
      enableCSIEncryption: false
# - name: rook-ceph-cluster
#   repo: https://charts.rook.io/release
#   version: v1.10.4
#   releaseName: rook-ceph-cluster
#   namespace: rook-ceph
#   includeCRDs: true
#   valuesInline:
#     cephClusterSpec:
#       external: 
#         enabled: true
#       dashboard:
#         ssl: false
#     toolbox: 
#       enabled: true


# patches:
#   - patch: |
#       apiVersion: batch/v1
#       kind: Job
#       metadata:
#         name: hook
#       $patch: delete
#     target:
#       annotationSelector: "helm.sh/hook=pre-delete"
