apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator: []
# - name: docker-config
#   options:
#     disableNameSuffixHash: true
#   files:
#   - config.json=config/config.json

resources:
- vault-rbac.yaml
- wf-rbac.yaml
- workflow-template.yaml
- event-bus.yaml