apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: kratos
  repo: https://k8s.ory.sh/helm/charts
  version: v0.28.2
  releaseName: kratos
  namespace: salesbot
  includeCRDs: true
  valuesInline:
    kratos:
      development: true
      config:
        dsn: postgres://foo:bar@pg-sqlproxy-gcloud-sqlproxy:5432/db
        secrets:
          default:
            - dolore occaecat nostrud Ut
            - sit et commodoaute ut voluptate consectetur Duis
        identity:
          default_schema_id: default
          schemas:
            - id: default
              url: file:///etc/config/identity.default.schema.json
        courier:
          smtp:
            connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
        selfservice:
          default_browser_return_url: http://127.0.0.1:4455/
      automigration:
        enabled: true
      identitySchemas:
        "identity.default.schema.json": |
          {
            "$id": "https://schemas.ory.sh/presets/kratos/identity.email.schema.json",
            "$schema": "http://json-schema.org/draft-07/schema#",
            "title": "Person",
            "type": "object",
            "properties": {
              "traits": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "format": "email",
                    "title": "E-Mail",
                    "ory.sh/kratos": {
                      "credentials": {
                        "password": {
                          "identifier": true
                        }
                      },
                      "recovery": {
                        "via": "email"
                      },
                      "verification": {
                        "via": "email"
                      }
                    }
                  }
                },
                "required": [
                  "email"
                ],
                "additionalProperties": false
              }
            }
          }