kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-discovery
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-discovery
roleRef:
  kind: Role
  name: vault-discovery
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: vault
