apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitea-tls
spec:
  # Secret names are always required.
  secretName: gitea-tls
  dnsNames:
    - git.dmann.xyz
    - git.dmann.dev
  # Issuer references are always required.
  issuerRef:
    name: letsencrypt
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer