apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- certificate.yaml
- oidc-secretclass.yaml
- vault-rbac.yaml
- sa.yaml

patches:
- |
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: gitea
  spec:
    template:
      spec:
        serviceAccountName: gitea

helmCharts:
- name: gitea
  repo: https://dl.gitea.io/charts/
  version: 8.0.2
  releaseName: gitea
  namespace: gitea
  includeCRDs: true
  valuesInline:
    image:
      registry: harbor.dmann.dev
      repository: docker.io/gitea/gitea
      tag: 1.18-dev
    dnsConfig: 
      options:
      - name: ndots
        value: "1" 
    containerSecurityContext:
      capabilities:
        add:
        - SYS_CHROOT


    ## @param extraVolumes Additional volumes to mount to the Gitea statefulset
    extraVolumes:
    - name: gitea-tls
      secret:
        secretName: gitea-tls
    - name: vault-oidc
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: vault-gitea-oidc-client

    ## @param extraContainerVolumeMounts Mounts that are only mapped into the Gitea runtime/main container, to e.g. override custom templates.
    extraContainerVolumeMounts:
    - name: gitea-tls
      mountPath: /opt/gitea-tls
    - name: vault-oidc
      mountPath: /run/secrets/oidc
    service:
      http:
        ipFamilyPolicy: PreferDualStack
        clusterIP: ""
      ssh:
        ipFamilyPolicy: PreferDualStack
        clusterIP: ""
    gitea:
      oauth:
      - name: 'vault'
        provider: openidConnect
        existingSecret: vault-gitea-oidc-client-secret
        autoDiscoverUrl: https://vault.homelab.dmann.xyz:8200/v1/identity/oidc/provider/default/.well-known/openid-configuration
      config:
        server:
          PROTOCOL: https
          DOMAIN: git.dmann.xyz
          CERT_FILE: /opt/gitea-tls/tls.crt
          KEY_FILE: /opt/gitea-tls/tls.key
        service:
          DISABLE_REGISTRATION: true
        webhook:
          ALLOWED_HOST_LIST: "*"