apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
helmCharts:
- name: gitea
  repo: https://dl.gitea.io/charts/
  version: 6.0.3
  releaseName: gitea
  namespace: gitea
  includeCRDs: true
  valuesInline:
    dnsConfig: 
      options:
      - name: ndots
        value: "1"
    service:
      http:
        ipFamilyPolicy: PreferDualStack
        clusterIP: ""
      ssh:
        ipFamilyPolicy: PreferDualStack
        clusterIP: ""
    gitea:
      config:
        server:
          DOMAIN: gitea.dmann.xyz