apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-gitea-oidc-client
spec:
  provider: vault
  secretObjects:
  - secretName: vault-gitea-oidc-client-secret
    type: Opaque
    data:
    - objectName: client-id
      key: key
    - objectName: client-secret
      key: secret
  parameters:
    roleName: 'gitea-client'
    objects: |
      - objectName: "client-id"
        secretPath: "identity/oidc/client/gitea"
        secretKey: "client_id"
      - objectName: "client-secret"
        secretPath: "identity/oidc/client/gitea"
        secretKey: "client_secret"