apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-dns-cloudflare-token
spec:
  provider: vault
  parameters:
    roleName: cloudflare-api
    objects: |
      - objectName: "token"
        secretPath: "secret/data/cloudflare-api"
        secretKey: "token"