apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: cloudflare-dns-resources
spec:
  template:
    serviceAccountName: cloudflaredns-event-sa # assign a service account with `get`, `list` and `watch` permissions on the resource being watched.
    dnsConfig:
      options:
      - name: ndots
        value: "1"
  resource:
    service-resource-updated:
      namespace: ""
      # resource group
      group: ""
      # resource version
      version: v1
      # resource kind
      resource: services
      filter: ~
      eventTypes:
        - ADD
        - DELETE
        - UPDATE