apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plex-tls
spec:
  secretName: plex-tls
  dnsNames:
    - plex.dmann.xyz
    - plex.dmann.dev
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  keystores:
    pkcs12:
      create: true
      passwordSecretRef: 
        key: password
        name: plex-tls-pkcs12-password