apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex-server
  template:
    metadata:
      labels:
        app: plex-server
    spec:

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: feature.node.kubernetes.io/pci-1013.present
                operator: Exists
              - key: feature.node.kubernetes.io/pci-10de.present
                operator: Exists
    
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      volumes:
      - name: plex-tls
        secret:
          secretName: plex-tls
          defaultMode: 0777
      - name: plex-tls-pkcs12-password
        secret:
          secretName: plex-tls-pkcs12-password
          defaultMode: 0777
      - name: media-nfs
        nfs:
          server: ceph.homelab.dmann.xyz
          path: /homelab/media
      - name: plex-config-data
        persistentVolumeClaim:
          claimName: plex-config-data
      - name: transcode-storage # Idea being we would mount a dedicated ssd storage class pvc here
        hostPath:
          path: /tmp/plex-transcoder
      - name: dev
        hostPath:
          path: /dev\
      containers:
      - name: plex-server
        securityContext:
          privileged: true
        image: lscr.io/linuxserver/plex:latest
        volumeMounts:
        - name: media-nfs
          mountPath: /media
        - name: plex-config-data
          mountPath: /config
        - name: transcode-storage
          mountPath: /transcode
        - name: plex-tls
          mountPath: /opt/plex-tls
        - name: plex-tls-pkcs12-password
          mountPath: /opt/plex-tls-pkcs12-password
        - name: gpu
          mountPath: /dev/
        # - name: gpu-lib
        #   mountPath: /usr/lib/x86_64-linux-gnu/
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: VERSION
          value: "docker"
        - name: ALLOWED_NETWORKS
          value: "10.0.0.0/8,192.168.0.0/16,172.16.0.0/12"
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: all

        ports:
        - name:  webui
          containerPort:  32400
          protocol: TCP
        - containerPort:  3005
          protocol: TCP
        - containerPort:  8324
          protocol: TCP
        - containerPort:  32469
          protocol: TCP
        
        - containerPort:  32410
          protocol: UDP
        - containerPort:  32412
          protocol: UDP
        - containerPort:  32413
          protocol: UDP
        - containerPort:  32414
          protocol: UDP
        resources:
          limits:
            memory: "3Gi"
            cpu: "4"