apiVersion: v1
kind: Service
metadata:
  name: plex
  annotations:
    k8s.dmann.xyz/cloudflare-domain-dmann-xyz: plex
    k8s.dmann.xyz/cloudflare-zone-dmann-xyz: dmann.xyz
    k8s.dmann.xyz/cloudflare-domain-dmann-dev: plex
    k8s.dmann.xyz/cloudflare-zone-dmann-dev: dmann.dev
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: plex-server
  ports:
  - port: 443
    targetPort: webui

---

apiVersion: v1
kind: Service
metadata:
  name: plex-server
spec:
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv4
  selector:
    app: plex-server
  ports:
  - port: 443
    targetPort: webui