apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: argo-cd
  repo: https://argoproj.github.io/argo-helm
  version: 3.33.6
  releaseName: argocd
  namespace: argocd
  includeCRDs: true
  valuesInline: 
    singleNamespace: true
    apiVersionOverrides:
      certmanager: cert-manager.io/v1
      ingress: networking.k8s.io/v1beta1
    server:
      certificate:
        enabled: true
        domain: argocd.homelab.dmann.xyz
        issuer:
          kind: ClusterIssuer
          name: homelab
        additionalHosts: []

- name: argocd-applicationset
  repo: https://argoproj.github.io/argo-helm
  version: 1.10.0
  releaseName: argocd-applicationset
  namespace: argocd
  includeCRDs: true
  valuesInline: 
    singleNamespace: true