apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: mdns-tunnel-config
    files:
    - default.yaml=config/default.yaml
resources:
- deployment.yaml
- service.yaml
# - certificate.yaml
