apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      volumes:
      - name: radarr-tls
        secret:
          secretName: radarr-tls
          defaultMode: 0777
      - name: media-nfs
        nfs:
          server: ceph.homelab.dmann.xyz
          path: /homelab/media
      - name: radarr-config-data
        persistentVolumeClaim:
          claimName: radarr-config-data
      containers:
      - name: radarr
        image: lscr.io/linuxserver/radarr:latest
        volumeMounts:
        - name: media-nfs
          mountPath: /media
        - name: radarr-config-data
          mountPath: /config
        - name: radarr-tls
          mountPath: /opt/radarr-tls
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Australia/Sydney"

        ports:
        - name:  webui
          containerPort:  7878
          protocol: TCP
        resources:
        #   limits:
        #     memory: "4Gi"
        #     cpu: "4"