apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: postgres-config
  literals:
    - POSTGRES_DB=postgresdb
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=psltest
resources:
- postgres-service.yaml
- postgres-statefulset.yaml