apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv4
  clusterIP: None
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: postgres
  type: ClusterIP
  selector:
    app: postgres