apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: hydra
  repo: https://k8s.ory.sh/helm/charts
  version: 0.49.2
  releaseName: hydra
  namespace: salesbot
  includeCRDs: true
  valuesInline:
    hydra:
      config:
        dsn: postgres://foo:bar@baz:1234/db'
        secrets:
          system:
          - 'randomsecret'
          
        urls:
          self:
            issuer: https://my-hydra/'
          login: https://my-idp/login'
          consent: https://my-idp/consent'