---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
healthzBindAddress: "::"
cgroupDriver: systemd
address: "::"

---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: stable
controlPlaneEndpoint: "cluster.homelab.dmann.xyz:6443"
clusterName: "homelab"
networking:
  podSubnet: "10.240.0.0/16,2403:5806:97ec:6300::/56"
  serviceSubnet: "10.241.0.0/16,2403:5806:97ec:6400::/112"
apiServer:
  certSANs:
  - cluster.homelab.dmann.xyz
  - "*.cluster.homelab.dmann.xyz"
  extraArgs:
    bind-address: "::"
    permit-address-sharing: "true"
    # oidc-issuer-url: https://vault.homelab.dmann.xyz:8200/v1/identity/oidc/provider/default
    # oidc-client-id: $oidcClientId
    # oidc-username-claim: email
    # oidc-groups-claim: groups
controllerManager:
  extraArgs:
    bind-address: "::"
    permit-address-sharing: "true"
scheduler:
  extraArgs:
    bind-address: "::"
    permit-address-sharing: "true"
etcd:
    external:
      endpoints: ["https://etcd-0.ordiri:2379", "https://etcd-1.ordiri:2379", "https://etcd-2.ordiri:2379"]
      caFile: /etc/ssl/certs/etcd-ca.crt
      certFile: /etc/ssl/certs/etcd.crt
      keyFile: /etc/ssl/private/etcd.key