apiVersion: crd.projectcalico.org/v1
kind: BGPConfiguration
metadata:
  name: default
spec:
  nodeToNodeMeshEnabled: false
  logSeverityScreen: Info
  asNumber: 65003
  serviceClusterIPs:
  - cidr: "2403:5807:c863:6400::/112"
  - cidr: "10.241.0.0/16"
---
apiVersion: crd.projectcalico.org/v1
kind: BGPPeer
metadata:
  name: "ordiri-cloud-router-masters"
spec:
  peerIP: "fd49:32ac:7d20:fffe::a0f9"
  asNumber: 65002 # From the router
---
apiVersion: crd.projectcalico.org/v1
kind: BGPPeer
metadata:
  name: "ordiri-cloud-router-workers"
spec:
  peerIP: "fd49:32ac:7d20:fffe::6d74"
  asNumber: 65002 # From the router
---
apiVersion: crd.projectcalico.org/v1
kind: BGPPeer
metadata:
  name: "ordiri-cloud-router-masters-4"
spec:
  peerIP: "10.0.100.37"
  asNumber: 65002 # From the router
---
apiVersion: crd.projectcalico.org/v1
kind: BGPPeer
metadata:
  name: "ordiri-cloud-router-workers-4"
spec:
  peerIP: "10.0.100.12"
  asNumber: 65002 # From the router