apiVersion: crd.projectcalico.org/v1
kind: BGPConfiguration
metadata:
  name: default
  namespace: calico-system
spec:
  nodeToNodeMeshEnabled: false
  logSeverityScreen: Info
  asNumber: 65003
  serviceClusterIPs:
  - cidr: "2403:5806:97ec:6400::/112"
  - cidr: "10.241.0.0/16"
---
apiVersion: crd.projectcalico.org/v1
kind: BGPPeer
metadata:
  name: "ordiri-cloud-router-masters"
  namespace: calico-system
spec:
  peerIP: "fd49:32ac:7d20:fffe::6d74"
  asNumber: 65002 # From the router
---
apiVersion: crd.projectcalico.org/v1
kind: BGPPeer
metadata:
  name: "ordiri-cloud-router-workers"
  namespace: calico-system
spec:
  peerIP: "fd49:32ac:7d20:fffe::a0f9"
  asNumber: 65002 # From the router