apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tigera-operator
resources:
- namespace.yaml
- bgp.yaml
helmCharts:
- name: tigera-operator
  repo: https://docs.projectcalico.org/charts
  version: v3.24.3
  releaseName: calico
  namespace: tigera-operator
  includeCRDs: true
  valuesInline:
    installation:
      calicoNetwork:
        # linuxDataplane: bpf
        ipPools:
        - cidr: 2403:5806:97ec:6300::/56
          blockSize: 122
          natOutgoing: "Disabled"
          disableBGPExport: false
          nodeSelector: all()
          encapsulation: None
        - cidr: 10.240.0.0/16
          blockSize: 26
          disableBGPExport: false
          natOutgoing: Enabled
          encapsulation: None
          nodeSelector: all()
        containerIPForwarding: Enabled
        nodeAddressAutodetectionV4:
          kubernetes: NodeInternalIP
        nodeAddressAutodetectionV6: 
          cidrs:
          - "2403:5806:97ec::/48"


# kubectl debug -it calicoctl --image=alpine