# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  external_url: "https://home-assistant.dmann.xyz:443"
  internal_url: "https://home-assistant.dmann.xyz:443"
  media_dirs: {}
  packages: !include_dir_merge_named packages/
  
recorder:
  db_url: postgresql://admin:psltest@postgres.home-assistant.svc.cluster.local:5432/postgresdb
  purge_keep_days: 365
  
tts:
- platform: google_translate

http:
  ssl_certificate: /opt/home-assistant-tls/tls.crt
  ssl_key: /opt/home-assistant-tls/tls.key

logger:
  default: warning

automation: !include automations.yaml
automation backups:
- alias: "Backup Home Assistant every night at 3 AM"
  id: backup_home_assistant_daily
  trigger:
    platform: time
    at: "03:00:00"
  action:
    alias: "Create backup now"
    service: backup.create
# This is no longer a thing, you *have* to use the UI 🙃
# mqtt:
#   broker: mqtt.dmann.xyz
#   port: 443
#   client_id: home-assistant-01
#   discovery: true
#   tls_insecure: false
#   certificate: /opt/home-assistant-tls/tls.crt
#   client_key: /opt/home-assistant-tls/tls.key
#   birth_message:
#     topic: 'homeassistant/status'
#     payload: 'online'
#   will_message:
#     topic: 'homeassistant/status'
#     payload: 'offline'
#  certificate: auto
# # Load frontend themes from the themes folder
# frontend:
#   themes: !include_dir_merge_named themes

# # Text to speech
# tts:
#   - platform: google_translate

# automation: !include automations.yaml
# script: !include scripts.yaml
# scene: !include scenes.yaml