apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blog-tls
spec:
  secretName: blog-tls
  dnsNames:
    - blog.dmann.xyz
    - blog.dmann.xyz
    - dmann.dev
    - dmann.xyz
  issuerRef:
    name: zerossl
    kind: ClusterIssuer