apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: caddyfile
    files:
    - "Caddyfile=./config/Caddyfile"
  - name: blogposts
    files:
    - "index.html=./pages/index.html"
resources:
  - deployment.yaml
  - service.yaml
  - certificate.yaml