policies:
- name: allow_secrets
  rules: path "secret/*" {
    capabilities = ["create", "read", "update", "delete", "list"]
    }
# Allow every pod in the application namespace to use the secret kv store
auth:
- type: kubernetes
  roles:
  - name: application
    bound_service_account_names: ["default"]
    bound_service_account_namespaces: ["application"]
    policies: allow_secrets
    ttl: 1h
        
secrets:
- path: secret
  type: kv
  description: General secrets.
  options:
    version: 2