apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zigbee2mqtt-tls
spec:
  secretName: zigbee2mqtt-tls
  dnsNames:
    - zigbee2mqtt.dmann.xyz
    - zigbee2mqtt.dmann.dev
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer