apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
spec:
  selector:
    matchLabels:
      app: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      containers:
      - name: zigbee2mqtt
        image: harbor.dmann.dev/docker.io/koenkk/zigbee2mqtt
        env:
        - name: DEBUG
        value: 'zigbee-herdsman*'
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: webui
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: mqtt
        readinessProbe:
          tcpSocket:
            port: mqtt
        volumeMounts:
        - name: zigbee2mqtt-config
          mountPath: /app/data/configuration.yaml
          subPath: configuration.yaml
      volumes:
      - name: zigbee2mqtt-config
        configMap:
          name: zigbee2mqtt-config