apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: zigbee2mqtt-config
    files:
    - configuration.yaml=config/configuration.yaml
  - name: zigbee2mqtt-custom-components
    files:
    - power-meter.js=components/esp-c6-power-meter.js
resources:
- statefulset.yaml
- ingress.yaml
- service.yaml
- certificate.yaml
- sa.yaml
- vault-rbac.yaml
