apiVersion: v1
kind: Service
metadata:
  name: zigbee2mqtt
spec:
  clusterIP: None
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv4
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: oauth2-proxy
  - name: zigbee2mqtt
    port: 8080
    protocol: TCP
    targetPort: webui
  type: ClusterIP
  selector:
    app: zigbee2mqtt