apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: salesbot-app-tls
spec:
  secretName: salesbot-app-tls
  dnsNames:
    - app.voxora.ai
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer