apiVersion: apps/v1
kind: Deployment
metadata:
  name: salesbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: salesbot
  template:
    metadata:
      labels:
        app: salesbot
    spec:
      volumes:
      - name: caddyfile
        configMap:
          name: caddyfile
      - name: salesbot-tls
        secret:
          secretName: salesbot-tls
      containers:
      - name: caddy
        image: docker.io/caddy:latest
        volumeMounts:
        - name: caddyfile
          mountPath: /opt/caddyfile
        - name: salesbot-tls
          mountPath: /opt/salesbot-tls
        readinessProbe:
          httpGet:
            path: /live
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /live
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        command:
        - caddy
        args:
        - run
        - --config
        - /opt/caddyfile/Caddyfile
        ports:
        - name:  http
          containerPort: 80
          protocol: TCP
        - name:  https
          containerPort: 443
          protocol: TCP
        resources:
      - name: salesbot
        image: harbor.dmann.dev/default/salesbot:pending
        readinessProbe:
          httpGet:
            path: /live
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /live
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        command:
        - /salesbot
        args:
        - '[::]:8181'
        ports:
        - name: salesbotws
          containerPort: 8181
          protocol: TCP