apiVersion: apps/v1
kind: Deployment
metadata:
  name: salesbot-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: salesbot-website
  template:
    metadata:
      labels:
        app: salesbot-website
    spec:
      volumes:
      - name: caddyfile
        configMap:
          name: caddyfile-website
      - name: salesbot-website-tls
        secret:
          secretName: salesbot-website-tls
      - name: webfiles
        emptyDir: {}
      initContainers:
      - name: voxora-ai
        image: harbor.dmann.dev/default/salesbot:pending
        volumeMounts:
        - name: caddyfile
          mountPath: /opt/caddyfile
        - name: salesbot-website-tls
          mountPath: /opt/salesbot-website-tls
        - name: webfiles
          mountPath: /opt/website
        command:
        - cp
        args:
        - -Rf
        - /website
        - /opt/website
      containers:
      - name: caddy
        image: docker.io/caddy:latest
        volumeMounts:
        - name: caddyfile
          mountPath: /opt/caddyfile
        - name: salesbot-website-tls
          mountPath: /opt/salesbot-website-tls
        - name: webfiles
          mountPath: /opt/website
        readinessProbe:
          httpGet:
            path: /live
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /live
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        command:
        - caddy
        args:
        - run
        - --config
        - /opt/caddyfile/Caddyfile
        ports:
        - name:  http
          containerPort: 80
          protocol: TCP
        - name:  https
          containerPort: 443
          protocol: TCP
        resources: