apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: caddyfile
    files:
    - "Caddyfile=./config/Caddyfile"
resources:
  - deployment.yaml
  - deployment-website.yaml
  - service.yaml
  - certificate.yaml