apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: caddyfile-app
    files:
    - "Caddyfile=./config/Caddyfile.app"
  - name: caddyfile-website
    files:
    - "Caddyfile=./config/Caddyfile.website"
resources:
- ../../../common/components/postgres
- deployment.yaml
- deployment-website.yaml
- service.yaml
- certificate-website.yaml
- certificate-app.yaml
