apiVersion: v1
kind: Service
metadata:
  name: salesbot
  annotations:
    k8s.dmann.xyz/cloudflare-domain-dmann-xyz: salesbot
    k8s.dmann.xyz/cloudflare-zone-dmann-xyz: dmann.xyz
    k8s.dmann.xyz/cloudflare-domain-dmann-dev: salesbot
    k8s.dmann.xyz/cloudflare-zone-dmann-dev: dmann.dev
    
    k8s.dmann.xyz/cloudflare-domain-voxora-app: 'app'
    k8s.dmann.xyz/cloudflare-zone-voxora-app: voxora.ai

    k8s.dmann.xyz/cloudflare-domain-voxora-root: ''
    k8s.dmann.xyz/cloudflare-zone-voxora-root: voxora.ai
    
    k8s.dmann.xyz/cloudflare-domain-voxora-www: 'www'
    k8s.dmann.xyz/cloudflare-zone-voxora-www: voxora.ai
spec:
  selector:
    app: salesbot
  ipFamilyPolicy: PreferDualStack
  ports:
  - port: 80
    name: http
  - port: 443
    name: https

---

apiVersion: v1
kind: Service
metadata:
  name: salesbot-website
  annotations:
    k8s.dmann.xyz/cloudflare-domain-voxora-root: ''
    k8s.dmann.xyz/cloudflare-zone-voxora-root: voxora.ai
    
    k8s.dmann.xyz/cloudflare-domain-voxora-www: 'www'
    k8s.dmann.xyz/cloudflare-zone-voxora-www: voxora.ai
spec:
  selector:
    app: salesbot-web
  ipFamilyPolicy: PreferDualStack
  ports:
  - port: 443
    name: https

