apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- grafana-service.yaml

helmCharts:
- name: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  version: 43.1.4
  releaseName: prometheus
  namespace: monitoring
  includeCRDs: true
  valuesInline:
    kubeEtcd:
      enabled: false