apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- prometheus-service.yaml
- grafana-service.yaml
- certificate.yaml
- vault-rbac.yaml

helmCharts:
- name: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  version: 45.1.1
  releaseName: prometheus
  namespace: monitoring
  includeCRDs: true
  valuesInline:
    kubeEtcd:
      enabled: false
    grafana:
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
          - name: provider-site
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            editable: false
            options:
              path: /var/lib/grafana/dashboards/provider-site
      dashboards:
        provider-site:
          hashicorp-vault:
            gnetId: 12904
            revision: 2
            datasource: Prometheus
          cert-manager:
            gnetId: 11001
            revision: 1
            datasource: Prometheus
          argocd:
            gnetId: 14584
            revision: 1
            datasource: Prometheus
      defaultDashboardsTimezone: Australia/Sydney
      sidecar:
        datasources:
          skipReload: true
          initDatasources: true
        dashboards:
          skipReload: true
        plugins:
          skipReload: true
          initPlugins: true
        notifiers:
          skipReload: true
          initNotifiers: true
      extraContainerVolumes:
      - name: grafana-tls
        secret:
          secretName: grafana-tls

      grafana.ini:
        server:
          protocol: https
          domain: grafana.dmann.dev
          root_url: https://grafana.dmann.dev/
          cert_file: /opt/grafana-tls/tls.crt
          cert_key: /opt/grafana-tls/tls.key
        auth.generic_oauth:
          name: OAuth
          icon: signin
          enabled: true
          client_id: $__file{/vault/secrets/oidc-id}
          client_secret: $__file{/vault/secrets/oidc-secret}
          scopes: openid profile email groups user
          empty_scopes: false
          auth_url: https://vault.homelab.dmann.xyz:8200/ui/vault/identity/oidc/provider/default/authorize
          token_url: https://vault.homelab.dmann.xyz:8200/v1/identity/oidc/provider/default/token
          api_url: https://vault.homelab.dmann.xyz:8200/v1/identity/oidc/provider/default/userinfo
          allowed_domains: dmann.xyz dmann.dev
          allow_sign_up: true
          tls_skip_verify_insecure: false

patches:
  - |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: prometheus-grafana
      namespace: monitoring
    spec:
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/role: grafana
            vault.hashicorp.com/agent-inject-secret-oidc-id: identity/oidc/client/grafana
            vault.hashicorp.com/agent-inject-template-oidc-id: |
              {{- with secret "identity/oidc/client/grafana" -}}
              {{ .Data.client_id }}
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-oidc-secret: identity/oidc/client/grafana
            vault.hashicorp.com/agent-inject-template-oidc-secret: |
              {{- with secret "identity/oidc/client/grafana" -}}
              {{ .Data.client_secret }}
              {{- end }}
        spec:
          containers:
          - name: grafana
            volumeMounts:
            - mountPath: /opt/grafana-tls
              name: grafana-tls
            readinessProbe:
              httpGet:
                scheme: HTTPS
              initialDelaySeconds: 30
            livenessProbe:
              httpGet:
                scheme: HTTPS