apiVersion: v1
kind: Service
metadata:
  name: prometheus-ingress
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: http-web
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: prometheus
  sessionAffinity: None
  type: ClusterIP