apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prowlarr
spec:
  serviceName: prowlarr
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      volumes:
      - name: prowlarr-tls
        secret:
          secretName: prowlarr-tls
          defaultMode: 0777
      - name: media-nfs
        nfs:
          server: ceph.homelab.dmann.xyz
          path: /homelab/media
      - name: prowlarr-config-data
        persistentVolumeClaim:
          claimName: prowlarr-config-data
      containers:
      - name: prowlarr
        image: lscr.io/linuxserver/prowlarr:develop
        volumeMounts:
        - name: media-nfs
          mountPath: /media
        - name: prowlarr-config-data
          mountPath: /config
        - name: prowlarr-tls
          mountPath: /opt/prowlarr-tls
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Australia/Sydney"

        ports:
        - name:  webui
          containerPort:  9696
          protocol: TCP
        resources:
        #   limits:
        #     memory: "4Gi"
        #     cpu: "4"