apiVersion: v1
kind: Service
metadata:
  name: radarr-ingress
  annotations:
    k8s.dmann.xyz/cloudflare-domain-dmann-xyz: radarr
    k8s.dmann.xyz/cloudflare-zone-dmann-xyz: dmann.xyz
    k8s.dmann.xyz/cloudflare-domain-dmann-dev: radarr
    k8s.dmann.xyz/cloudflare-zone-dmann-dev: dmann.dev
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: oauth2-proxy
  selector:
    app: radarr
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
spec:
  clusterIP: None
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv4
  selector:
    app: radarr
  ports:
  - port: 7878
    targetPort: webui