apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cloudflare-secretclass.yaml
- zerossl-secretclass.yaml
- vault-rbac.yaml
- letsencrypt-staging-clusterissuer.yaml
- letsencrypt-clusterissuer.yaml
- zerossl-clusterissuer.yaml
- test-certificate.yaml
helmCharts:
- name: cert-manager
  repo: https://charts.jetstack.io
  version: v1.12.3
  releaseName: cert-manager
  namespace: cert-manager
  includeCRDs: true
  valuesInline:
    global:
      leaderElection: 
        namespace: cert-manager
    installCRDs: true

patches:
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cert-manager
      namespace: cert-manager
    spec:
      template:
        spec:
          volumes:
          - name: cloudflare-api
            csi:
              driver: secrets-store.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: "vault-cert-manager-cloudflare-token"
          - name: zerossl-api
            csi:
              driver: secrets-store.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: "vault-cert-manager-zerossl-token"
          containers:
          - name: cert-manager-controller
            volumeMounts:
            - name:  cloudflare-api
              mountPath:  /run/secrets/cloudflare-api
            - name:  zerossl-api
              mountPath:  /run/secrets/zerossl-api
