apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: cert-manager
  repo: https://charts.jetstack.io
  version: v1.10.0
  releaseName: cert-manager
  namespace: cert-manager
  includeCRDs: true
  valuesInline:
    global:
      leaderElection: 
        namespace: cert-manager
    installCRDs: true
