apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-cert-manager-cloudflare-token
spec:
  provider: vault
  secretObjects:
  - secretName: vault-cert-manager-cloudflare-token
    type: Opaque
    data:
    - objectName: token
      key: token
  parameters:
    roleName: cloudflare-api
    objects: |
      - objectName: "token"
        secretPath: "secret/data/cloudflare-api"
        secretKey: "token"