apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test
spec:
  # Secret names are always required.
  secretName: test-tls
  dnsNames:
    - test-tls.dmann.xyz
    - test-tls.dmann.dev
  # Issuer references are always required.
  issuerRef:
    name: letsencrypt-staging
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer