apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-cert-manager-zerossl-token
spec:
  provider: vault
  secretObjects:
  - secretName: vault-cert-manager-zerossl-token
    type: Opaque
    data:
    - objectName: hmac
      key: hmac
    - objectName: kid
      key: kid
    - objectName: token
      key: token
  parameters:
    roleName: zerossl-api
    objects: |
      - objectName: "kid"
        secretPath: "secret/data/zerossl-api"
        secretKey: "kid"
      - objectName: "hmac"
        secretPath: "secret/data/zerossl-api"
        secretKey: "hmac"
      - objectName: "token"
        secretPath: "secret/data/zerossl-api"
        secretKey: "token"