apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab-applicationsets
spec:
  # goTemplate: true
  generators:
  - merge:
      mergeKeys:
      - path.basename
      generators:
      - git:
          repoURL: git@github.com:ordiri/ordiri.git
          revision: HEAD
          directories:
          - path: manifests/*/*
          - path: manifests/system/platform
            exclude: true
          - path: manifests/common/*
            exclude: true
          # For a specific cluster, enable Redis.
      - list:
          elements:
          - path.basename: k8-workshop
            argocd.image_updater.images: 'harbor.dmann.dev/default/kubernetes-course'
            argocd.image_updater.method: git
            argocd.image_updater.target: kustomize
            argocd.image_updater.update_strategy: latest
          - path.basename: salesbot
            argocd.image_updater.images: 'harbor.dmann.dev/default/salesbot'
            argocd.image_updater.method: git
            argocd.image_updater.target: kustomize
            argocd.image_updater.update_strategy: latest
          - path.basename: blog
            argocd.image_updater.images: 'harbor.dmann.dev/default/blog'
            argocd.image_updater.method: git
            argocd.image_updater.target: kustomize
            argocd.image_updater.update_strategy: latest

  template:
    metadata:
      name: '{{path.basename}}'
      annotations:
        argocd-image-updater.argoproj.io/image-list: '{{argocd.image_updater.images}}'
        argocd-image-updater.argoproj.io/write-back-method: '{{argocd.image_updater.method}}'
        argocd-image-updater.argoproj.io/write-back-target: '{{argocd.image_updater.target}}'
        argocd-image-updater.argoproj.io/update-strategy: '{{argocd.image_updater.update_strategy}}'

    spec:
      project: '{{path[1]}}'
      source:
        repoURL: git@github.com:ordiri/ordiri.git
        targetRevision: HEAD
        path: '{{path}}/overlays/default'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated: {}
        syncOptions:
        - ServerSideApply=true