apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab-applicationsets
spec:
  generators:
  - git:
      repoURL: https://github.com/ordiri/ordiri.git
      revision: HEAD
      directories:
      - path: manifests/*/*
      - path: manifests/system/platform
        exclude: true
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/ordiri/ordiri.git
        targetRevision: HEAD
        path: '{{path}}/overlays/default'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      # syncPolicy:
      #   automated:
      #     prune: true