apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform
spec:
  project: default
  source:
    repoURL: https://github.com/ordiri/ordiri.git
    targetRevision: HEAD
    path: manifests/system/platform/overlays/default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}
    syncOptions:
    - ServerSideApply=true