apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-limits-cpu: 100m
        vault.hashicorp.com/agent-requests-cpu: 50m
        vault.hashicorp.com/agent-limits-mem: 128Mi
        vault.hashicorp.com/agent-requests-mem: 64Mi
        vault.hashicorp.com/role: sonarr
        vault.hashicorp.com/agent-inject-secret-oidc: identity/oidc/client/sonarr
        vault.hashicorp.com/agent-inject-template-oidc: |
          {{- with secret "identity/oidc/client/sonarr" -}}
          export oidc_client_id="{{ .Data.client_id }}"
          export oidc_client_secret="{{ .Data.client_secret }}"
          {{- end }}
    spec:
      serviceAccount: sonarr
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      volumes:
      - name: sonarr-tls
        secret:
          secretName: sonarr-tls
          defaultMode: 0777
      - name: media-nfs
        nfs:
          server: ceph.homelab.dmann.xyz
          path: /homelab/media
      - name: sonarr-config-data
        persistentVolumeClaim:
          claimName: sonarr-config-data
      containers:
      - name: oauth2-proxy
        command:
        - sh
        - -c
        args:
        - |
          source /vault/secrets/oidc;
          /bin/oauth2-proxy \
          --provider=oidc \
          --email-domain=* \
          --oidc-email-claim=sub \
          --upstream=http://127.0.0.1:8989 \
          --https-address=[::]:4180 \
          --tls-cert-file=/opt/sonarr-tls/tls.crt \
          --tls-key-file=/opt/sonarr-tls/tls.key \
          --provider-display-name="Vault" \
          --client-id="${oidc_client_id}" \
          --client-secret="${oidc_client_secret}" \
          --redirect-url="https://sonarr.dmann.xyz" \
          --oidc-issuer-url="https://vault.homelab.dmann.xyz:8200/v1/identity/oidc/provider/default" \
          --cookie-secure=false \
          --cookie-secret=secret12secret12
        env: []
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        ports:
        - containerPort: 4180
          protocol: TCP
          name: oauth2-proxy
        resources: 
        volumeMounts:
        - name: sonarr-tls
          mountPath: /opt/sonarr-tls
      - name: sonarr
        image: lscr.io/linuxserver/sonarr:develop@sha256:eacd44a731dc31b913f2f0911ecc79cc1ebd1120747d38d6ca23d0da089ca76b
        volumeMounts:
        - name: media-nfs
          mountPath: /media
        - name: sonarr-config-data
          mountPath: /config
        - name: sonarr-tls
          mountPath: /opt/sonarr-tls
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Australia/Sydney"
        ports:
        - name:  webui
          containerPort:  8989
          protocol: TCP
        resources:
          requests:
            memory: "4Gi"
            cpu: "4"