apiVersion: v1
kind: Service
metadata:
  name: sonarr-ingress
  annotations:
    k8s.dmann.xyz/cloudflare-domain-dmann-xyz: sonarr
    k8s.dmann.xyz/cloudflare-zone-dmann-xyz: dmann.xyz
    k8s.dmann.xyz/cloudflare-domain-dmann-dev: sonarr
    k8s.dmann.xyz/cloudflare-zone-dmann-dev: dmann.dev
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: oauth2-proxy
  selector:
    app: sonarr
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
spec:
  clusterIP: None
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv4
  selector:
    app: sonarr
  ports:
  - port: 8989
    targetPort: webui