apiVersion: v1
kind: Service
metadata:
  name: zigbee2mqtt-ingress
  annotations:
    k8s.dmann.xyz/cloudflare-domain-dmann-xyz: zigbee2mqtt
    k8s.dmann.xyz/cloudflare-zone-dmann-xyz: dmann.xyz
    k8s.dmann.xyz/cloudflare-domain-dmann-dev: zigbee2mqtt
    k8s.dmann.xyz/cloudflare-zone-dmann-dev: dmann.dev
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: reverse-proxy
  sessionAffinity: None
  type: ClusterIP