apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: vault
  repo: https://helm.releases.hashicorp.com
  version: v0.23.0
  releaseName: vault
  namespace: vault
  includeCRDs: true
  valuesInline: 
    global:
      externalVaultAddr: https://vault.homelab.dmann.xyz:8200
    server:
      enabled: false
    csi:
      enabled: true
      image:
        repository: "harbor.dmann.dev/docker.io/hashicorp/vault-csi-provider"
    injector:
      enabled: true
      image:
        repository: "harbor.dmann.dev/docker.io/hashicorp/vault-k8s"
      agentImage:
        repository: "harbor.dmann.dev/docker.io/hashicorp/vault"
    