apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: vault
  repo: https://helm.releases.hashicorp.com
  version: 0.24.1
  releaseName: vault
  namespace: vault
  includeCRDs: true
  valuesInline: 
    global:
      externalVaultAddr: https://vault.homelab.dmann.xyz:8200
    server:
      enabled: false
    csi:
      enabled: true
      image:
        repository: "harbor.dmann.dev/docker.io/hashicorp/vault-csi-provider"
    injector:
      enabled: true
      image:
        repository: "harbor.dmann.dev/docker.io/hashicorp/vault-k8s"
      agentImage:
        repository: "harbor.dmann.dev/docker.io/hashicorp/vault"
        failurePolicy: Fail
      resources:
        requests:
          memory: 128Mi
          cpu: 50m
        limits:
          memory: 256Mi
          cpu: 100m