apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sabnzbd-tls
spec:
  secretName: sabnzbd-tls
  dnsNames:
    - sabnzbd.dmann.xyz
    - sabnzbd.dmann.dev
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer