apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config-data
spec:
  resources:
    requests:
      storage: 100G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-clone
spec:
  storageClassName: ceph-rbd
  dataSource:
    name: sabnzbd-config-data
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100G