apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-tls
spec:
  # Secret names are always required.
  secretName: argo-tls
  dnsNames:
    - argo.dmann.xyz
    - argo.dmann.dev
  # Issuer references are always required.
  issuerRef:
    name: letsencrypt
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer