apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: argo-workflows
  repo: https://argoproj.github.io/argo-helm
  version: 0.29.2
  releaseName: argo-workflows
  namespace: argo-workflows
  includeCRDs: true
  valuesInline: 
    server:
      secure: true
      extraArgs:
      - --auth-mode
      - client
      - --auth-mode
      - sso
      sso:
        rbac: 
          enabled: true
        issuer: https://vault.homelab.dmann.xyz:8200/v1/identity/oidc/provider/default
        clientId:
          name: vault-argo-oidc-client-secret
          key: client-id
        clientSecret:
          name: vault-argo-oidc-client-secret
          key: client-secret
        redirectUrl: https://argo.dmann.xyz/oauth2/callback
        scopes:
        - openid
        - profile
        - email
        - groups
      volumes:
      - name: argo-oidc-creds
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "vault-argo-oidc-client"
      volumeMounts:
      - name:  argo-oidc-creds
        mountPath:  /run/secrets/oidc
    controller:
      rbac:
        secretWhitelist: 
        - vault-argo-oidc-client-secret
      workflowNamespaces: []
      containerRuntimeExecutor: emissary
    executor:
      resources:
        limits:
          ephemeral-storage: 10Gi


resources:
- proxy
- certificate.yaml
- oidc-secretclass.yaml
- vault-rbac.yaml
- admin-sa.yaml
- readonly-sa.yaml