apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-argo-oidc-client
spec:
  provider: vault
  secretObjects:
  - secretName: vault-argo-oidc-client-secret
    type: Opaque
    data:
    - objectName: client-id # References clientId below
      key: client-id # Key within k8s secret for this value
    - objectName: client-secret
      key: client-secret
  parameters:
    roleName: 'argo-workflow-client'
    objects: |
      - objectName: "client-id"
        secretPath: "identity/oidc/client/argo-workflows"
        secretKey: "client_id"
      - objectName: "client-secret"
        secretPath: "identity/oidc/client/argo-workflows"
        secretKey: "client_secret"