apiVersion: v1
kind: ServiceAccount
metadata:
  name: readonly-workflow-user
  annotations:
    workflows.argoproj.io/rbac-rule: "true"
    workflows.argoproj.io/rbac-rule-precedence: "0"
---
apiVersion: v1
kind: Secret
metadata:
  name: readonly-workflow-user.service-account-token
  annotations:
    kubernetes.io/service-account.name: readonly-workflow-user
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: readonly-workflow-user-admin
rules:
- apiGroups:
  - "argoproj.io"
  resources:
  - "eventbus"
  - "eventsources"
  - "sensors"
  verbs:
  - "list"
  - "get"
  - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: readonly-workflow-user-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: readonly-workflow-user-admin
subjects:
- kind: ServiceAccount
  name: readonly-workflow-user
  namespace: argo-workflows